---
apiVersion: v1
kind: Namespace
metadata:
  name: nr-hcp-consul
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: nr-hcp-consul
  labels:
    app.kubernetes.io/name: collector-config
data:
  collector-config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: "hcp-consul"
              scrape_interval: 60s # Do not go any lower than this or you'll hit rate limits
              scheme: https
              dns_sd_configs:
                - names:
                    - "${HCP_ACCESS_URL}"
                  type: "A"
                  port: 443
              authorization:
                credentials: "${HCP_ACCESS_TOKEN}"
              metrics_path: "/v1/agent/metrics"
              # Skipping TLS verification based on Consul docs(https://developer.hashicorp.com/hcp/docs/consul/monitor/metrics#prometheus).
              tls_config:
                insecure_skip_verify: true
    
    processors:
      batch:

    exporters:
      otlphttp:
        endpoint: ${NEW_RELIC_OTLP_ENDPOINT}
        headers:
          api-key: ${NEW_RELIC_API_KEY}

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [otlphttp]
---
apiVersion: v1
kind: Pod
metadata:
  name: collector
  namespace: nr-hcp-consul
  labels:
    app.kubernetes.io/name: collector
spec:
  containers:
    - name: collector
      image: otel/opentelemetry-collector-contrib:0.98.0
      env:
        # The default US endpoint is set here. You can change the endpoint and port based on your requirements if needed.
        # docs: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-otlp/#configure-endpoint-port-protocol
        - name: NEW_RELIC_OTLP_ENDPOINT
          value: https://otlp.nr-data.net/
        # The New Relic API key used to authenticate export requests.
        # Defined in secrets.yaml
        - name: NEW_RELIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: nr-hcp-consul-secret
              key: NEW_RELIC_API_KEY
        # The HCP Consul access token.
        # Defined in secrets.yaml
        - name: HCP_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: nr-hcp-consul-secret
              key: HCP_ACCESS_TOKEN
        # The HCP Consul access url.
        # docs: https://developer.hashicorp.com/hcp/docs/consul/hcp-managed/access#get-access-url
        - name: HCP_ACCESS_URL
          value: <INSERT_HCP_ACCESS_URL>
      volumeMounts:
        - name: collector-config-vol
          mountPath: /etc/otelcol-contrib
  volumes:
    - name: collector-config-vol
      configMap:
        name: collector-config
        items:
          - key: collector-config
            path: config.yaml
