---
apiVersion: v1
kind: Namespace
metadata:
  name: nr-singlestore
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: nr-singlestore
  labels:
    app.kubernetes.io/name: collector-config
data:
  collector-config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: "singlestore"
              scrape_interval: 60s # Do not go any lower than this or you'll hit rate limits
              static_configs:
                - targets: ["api.singlestore.com"]
              scheme: https
              bearer_token: "${SINGLESTORE_API_KEY}"
              metrics_path: /v2/organizations/${SINGLESTORE_ORG_ID}/workspaceGroups/${SINGLESTORE_WORKSPACE_GROUP_ID}/metrics
    
    processors:
      batch:

    exporters:
      otlphttp:
        endpoint: ${NEW_RELIC_OTLP_ENDPOINT}
        headers:
          api-key: ${NEW_RELIC_API_KEY}

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [otlphttp]
---
apiVersion: v1
kind: Pod
metadata:
  name: collector
  namespace: nr-singlestore
  labels:
    app.kubernetes.io/name: collector
spec:
  containers:
    - name: collector
      image: otel/opentelemetry-collector-contrib:0.98.0
      env:
        # The default US endpoint is set here. You can change the endpoint and port based on your requirements if needed.
        # docs: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-otlp/#configure-endpoint-port-protocol
        - name: NEW_RELIC_OTLP_ENDPOINT
          value: https://otlp.nr-data.net/
        # The New Relic API key used to authenticate export requests.
        # Defined in secrets.yaml
        - name: NEW_RELIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: nr-singlestore-secret
              key: NEW_RELIC_API_KEY
        # The Singlestore API key.
        # Defined in secrets.yaml
        - name: SINGLESTORE_API_KEY
          valueFrom:
            secretKeyRef:
              name: nr-singlestore-secret
              key: SINGLESTORE_API_KEY
        # The Singlestore Org ID.
        # docs: https://support.singlestore.com/hc/en-us/articles/12396547132564-Workspace-Group-ID-or-Cluster-ID
        - name: SINGLESTORE_ORG_ID
          value: <INSERT_SINGLESTORE_ORG_ID>
        # The Singlestore Workspace Group ID.
        # docs: https://support.singlestore.com/hc/en-us/articles/12396547132564-Workspace-Group-ID-or-Cluster-ID
        - name: SINGLESTORE_WORKSPACE_GROUP_ID
          value: <INSERT_SINGLESTORE_WORKSPACE_GROUP_ID>
      volumeMounts:
        - name: collector-config-vol
          mountPath: /etc/otelcol-contrib
  volumes:
    - name: collector-config-vol
      configMap:
        name: collector-config
        items:
          - key: collector-config
            path: config.yaml
