extensions:
  health_check: {}
receivers:
  otlp:
    protocols:
      grpc:
  fluentforward:
    endpoint: 0.0.0.0:8006
processors:
  batch:
exporters:
  logging:
    logLevel: $LOG_EXPORTER_LOG_LEVEL
  otlp:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      "api-key": $NEW_RELIC_API_KEY
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp]
    traces:
      receivers: [otlp]
      processors: [ batch ]
      exporters: [logging, otlp]
    logs:
      receivers: [fluentforward]
      processors: [ batch ]
      exporters: [logging, otlp]
