version: '3'
services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.92.0
    command: --config=/etc/otelcol/config.yaml
    volumes:
      - ./otel-config.yaml:/etc/otelcol/config.yaml
      # Mount the host file system when running in docker so we can monitor the host system,
      # not the docker container. For more info see:
      # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver#collecting-host-metrics-from-inside-a-container-linux-only
      - /:/hostfs
    environment:
      NEW_RELIC_OTLP_ENDPOINT: ${NEW_RELIC_OTLP_ENDPOINT}
      NEW_RELIC_API_KEY: ${NEW_RELIC_API_KEY}
      HOST_METRICS_ROOT_PATH: /hostfs
    ports:
      - "4317:4317"     # OTLP grpc
      - "4318:4318"     # OTLP http
      - "13133:13133"   # health
