---
apiVersion: v1
kind: Namespace
metadata:
  name: nr-statsd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: nr-statsd
  labels:
    app.kubernetes.io/name: collector-config
data:
  collector-config: |
    receivers:
      statsd:
        endpoint: 0.0.0.0:8125
        is_monotonic_counter: true

    processors:
      batch:

    exporters:
      otlphttp:
        endpoint: ${NEW_RELIC_OTLP_ENDPOINT}
        headers:
          api-key: ${NEW_RELIC_API_KEY}

    service:
      pipelines:
        metrics:
          receivers: [statsd]
          processors: [batch]
          exporters: [otlphttp]
---
apiVersion: v1
kind: Pod
metadata:
  name: collector
  namespace: nr-statsd
  labels:
    app.kubernetes.io/name: collector
spec:
  containers:
    - name: collector
      image: otel/opentelemetry-collector-contrib:0.98.0
      env:
        # The default US endpoint is set here. You can change the endpoint and port based on your requirements if needed.
        # docs: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-otlp/#configure-endpoint-port-protocol
        - name: NEW_RELIC_OTLP_ENDPOINT
          value: https://otlp.nr-data.net/
        # The New Relic API key used to authenticate export requests.
        # Defined in secrets.yaml
        - name: NEW_RELIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: nr-statsd-secret
              key: NEW_RELIC_API_KEY
      volumeMounts:
        - name: collector-config-vol
          mountPath: /etc/otelcol-contrib
      ports:
        - containerPort: 8125
          protocol: UDP
  volumes:
    - name: collector-config-vol
      configMap:
        name: collector-config
        items:
          - key: collector-config
            path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: nr-statsd
  labels:
    app.kubernetes.io/name: collector
spec:
  ports:
    - name: statsd
      port: 8125
      protocol: UDP
  selector:
    app.kubernetes.io/name: collector
