---
apiVersion: v1
kind: Namespace
metadata:
  name: nr-redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: nr-redis
  labels:
    app.kubernetes.io/name: collector-config
data:
  collector-config: |
    receivers:
      redis:
        # Connect to redis pod defined in redis.yaml using service env vars set by k8s
        endpoint: ${REDIS_SERVICE_HOST}:${REDIS_SERVICE_PORT}
        metrics:
          # Enable redis.maxmemory optional metric
          redis.maxmemory:
            enabled: true
    
    processors:
      batch:
      # Add identifying resource attributes, which is required for New Relic entity synthesis. 
      # The redis receiver does not currently include any identifying attributes on the metrics it produces.
      # We manually assign values to server.address and server.port, since values for ${REDIS_SERVICE_HOST} and ${REDIS_SERVICE_PORT} are unstable.
      attributes/redis_metrics:
        include:
          match_type: regexp
          metric_names:
            # Notice that if with single or without quotes just one backslash is needed 'redis\..*'
            - "redis\\..*"
        actions:
          - action: upsert
            key: server.address
            value: "redis"
          - action: upsert
            key: server.port
            value: "6379"
    
    exporters:
      otlphttp:
        endpoint: ${NEW_RELIC_OTLP_ENDPOINT}
        headers:
          api-key: ${NEW_RELIC_API_KEY}
    
    service:
      pipelines:
        metrics:
          receivers: [redis]
          processors: [attributes/redis_metrics, batch]
          exporters: [otlphttp]
---
apiVersion: v1
kind: Pod
metadata:
  name: collector
  namespace: nr-redis
  labels:
    app.kubernetes.io/name: collector
spec:
  containers:
    - name: collector
      image: otel/opentelemetry-collector-contrib:0.98.0
      env:
        # The default US endpoint is set here. You can change the endpoint and port based on your requirements if needed.
        # docs: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-otlp/#configure-endpoint-port-protocol
        - name: NEW_RELIC_OTLP_ENDPOINT
          value: https://otlp.nr-data.net/
        # The New Relic API key used to authenticate export requests.
        # Defined in secrets.yaml
        - name: NEW_RELIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: nr-redis-secret
              key: NEW_RELIC_API_KEY
      volumeMounts:
        - name: collector-config-vol
          mountPath: /etc/otelcol-contrib
  volumes:
    - name: collector-config-vol
      configMap:
        name: collector-config
        items:
          - key: collector-config
            path: config.yaml
